steps:
- name: 'gcr.io/cloud-builders/docker'
args: [ 'build', '--tag', 'gcr.io/$PROJECT_ID/infra-as-code-tools:$TAG_NAME', '--file', '$_DOCKERFILE' ]
images:
- 'gcr.io/$PROJECT_ID/infra-as-code-tools:$TAG_NAME'
