FROM google/cloud-sdk:alpine
MAINTAINER "Ludovic Piot <ludovic.piot@thegaragebandofit.com>"

# Install prerequisites
RUN apk add openssl git jq vim

# GCP configuration
WORKDIR /

# GCP extra components install
RUN gcloud components install alpha --quiet && \
    gcloud components install beta --quiet && \
    gcloud components install kubectl --quiet && \
    gcloud components update --quiet

ENTRYPOINT [ "/bin/bash" ]
